name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Deploy al servidor
        run: |
          cd ~/proyectos/game
          git pull
          npm install
          pm2 restart game || pm2 start index.js --name "game"
